export const shoppingCart = [
  {
    cover: "./img/shopping-cart.jpg",
    name: "Pizza",
    price: 200,
    qty: 1,
    total: 200,
  },
  {
    cover: "./img/shopping-cart.jpg",
    name: "Pizza",
    price: 200,
    qty: 1,
    total: 200,
  },
  {
    cover: "./img/shopping-cart.jpg",
    name: "Pizza",
    price: 200,
    qty: 1,
    total: 200,
  },
  {
    cover: "./img/shopping-cart.jpg",
    name: "Pizza",
    price: 200,
    qty: 1,
    total: 200,
  },
  {
    cover: "./img/shopping-cart.jpg",
    name: "Pizza",
    price: 200,
    qty: 1,
    total: 200,
  },
  {
    cover: "./img/shopping-cart.jpg",
    name: "Pizza",
    price: 200,
    qty: 1,
    total: 200,
  },
  {
    cover: "./img/shopping-cart.jpg",
    name: "Pizza",
    price: 200,
    qty: 1,
    total: 200,
  },
];

export const categories = [
  {
    _id: "1",
    cover: "./img/category/burger.jpg",
    name: "Burger",
  },
  {
    _id: "2",
    cover: "./img/category/pizza.jpg",
    name: "Pizza",
  },
  {
    _id: "3",
    cover: "./img/category/sandwich.jpg",
    name: "Sandwich",
  },
  {
    _id: "4",
    cover: "./img/category/burger.jpg",
    name: "Burger",
  },
  {
    _id: "5",
    cover: "./img/category/pizza.jpg",
    name: "Pizza",
  },
  {
    _id: "6",
    cover: "./img/category/sandwich.jpg",
    name: "Sandwich",
  },
];

export const food = [
  {
    _id: "1",
    cover: "../img/food/b1.jpg",
    name: "Burger",
    price: "60",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum ipsa voluptates, iste quisquam, explicabo quos illum dicta iure libero fugit distinctio! Voluptate voluptas illum esse? Placeat accusantium impedit recusandae ratione. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates accusamus reiciendis maiores. Qui iure deserunt, dignissimos distinctio aut, at nobis in laudantium natus voluptatibus magni id, mollitia neque! Eos, magni.",
    category: "1",
    active: "Yes",
  },
  {
    _id: "2",
    cover: "../img/food/p1.jpg",
    name: "Pizza",
    price: "100",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum ipsa voluptates, iste quisquam, explicabo quos illum dicta iure libero fugit distinctio! Voluptate voluptas illum esse? Placeat accusantium impedit recusandae ratione. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates accusamus reiciendis maiores. Qui iure deserunt, dignissimos distinctio aut, at nobis in laudantium natus voluptatibus magni id, mollitia neque! Eos, magni.2",
    category: "2",
    active: "No",
  },
  {
    _id: "3",
    cover: "../img/food/s1.jpg",
    name: "Sandwich",
    price: "50",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum ipsa voluptates, iste quisquam, explicabo quos illum dicta iure libero fugit distinctio! Voluptate voluptas illum esse? Placeat accusantium impedit recusandae ratione. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates accusamus reiciendis maiores. Qui iure deserunt, dignissimos distinctio aut, at nobis in laudantium natus voluptatibus magni id, mollitia neque! Eos, magni.",
    category: "1",
    active: "Yes",
  },
  {
    _id: "4",
    cover: "../img/food/b2.jpg",
    name: "Burger",
    price: "60",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum ipsa voluptates, iste quisquam, explicabo quos illum dicta iure libero fugit distinctio! Voluptate voluptas illum esse? Placeat accusantium impedit recusandae ratione. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates accusamus reiciendis maiores. Qui iure deserunt, dignissimos distinctio aut, at nobis in laudantium natus voluptatibus magni id, mollitia neque! Eos, magni.",
    category: "4",
    active: "Yes",
  },
  {
    _id: "5",
    cover: "../img/food/p2.jpg",
    name: "Pizza",
    price: "200",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum ipsa voluptates, iste quisquam, explicabo quos illum dicta iure libero fugit distinctio! Voluptate voluptas illum esse? Placeat accusantium impedit recusandae ratione. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates accusamus reiciendis maiores. Qui iure deserunt, dignissimos distinctio aut, at nobis in laudantium natus voluptatibus magni id, mollitia neque! Eos, magni.",
    category: "3",
    active: "Yes",
  },
  {
    _id: "6",
    cover: "../img/food/s2.jpg",
    name: "Sandwich",
    price: "50",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum ipsa voluptates, iste quisquam, explicabo quos illum dicta iure libero fugit distinctio! Voluptate voluptas illum esse? Placeat accusantium impedit recusandae ratione. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates accusamus reiciendis maiores. Qui iure deserunt, dignissimos distinctio aut, at nobis in laudantium natus voluptatibus magni id, mollitia neque! Eos, magni.",
    category: "2",
    active: "Yes",
  },
  {
    _id: "7",
    cover: "../img/food/b1.jpg",
    name: "Burger",
    price: "60",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum ipsa voluptates, iste quisquam, explicabo quos illum dicta iure libero fugit distinctio! Voluptate voluptas illum esse? Placeat accusantium impedit recusandae ratione. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates accusamus reiciendis maiores. Qui iure deserunt, dignissimos distinctio aut, at nobis in laudantium natus voluptatibus magni id, mollitia neque! Eos, magni.",
    category: "1",
    active: "Yes",
  },
  {
    _id: "8",
    cover: "../img/food/p1.jpg",
    name: "Pizza",
    price: "200",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum ipsa voluptates, iste quisquam, explicabo quos illum dicta iure libero fugit distinctio! Voluptate voluptas illum esse? Placeat accusantium impedit recusandae ratione. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates accusamus reiciendis maiores. Qui iure deserunt, dignissimos distinctio aut, at nobis in laudantium natus voluptatibus magni id, mollitia neque! Eos, magni.",
    category: "1",
    active: "Yes",
  },
  {
    _id: "9",
    cover: "../img/food/s1.jpg",
    name: "Sandwich",
    price: "50",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum ipsa voluptates, iste quisquam, explicabo quos illum dicta iure libero fugit distinctio! Voluptate voluptas illum esse? Placeat accusantium impedit recusandae ratione. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates accusamus reiciendis maiores. Qui iure deserunt, dignissimos distinctio aut, at nobis in laudantium natus voluptatibus magni id, mollitia neque! Eos, magni.",
    category: "2",
    active: "Yes",
  },
  {
    _id: "10",
    cover: "../img/food/b2.jpg",
    name: "Burger",
    price: "60",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum ipsa voluptates, iste quisquam, explicabo quos illum dicta iure libero fugit distinctio! Voluptate voluptas illum esse? Placeat accusantium impedit recusandae ratione. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates accusamus reiciendis maiores. Qui iure deserunt, dignissimos distinctio aut, at nobis in laudantium natus voluptatibus magni id, mollitia neque! Eos, magni.",
    category: "3",
    active: "Yes",
  },
  {
    _id: "11",
    cover: "../img/food/p2.jpg",
    name: "Pizza",
    price: "200",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum ipsa voluptates, iste quisquam, explicabo quos illum dicta iure libero fugit distinctio! Voluptate voluptas illum esse? Placeat accusantium impedit recusandae ratione. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates accusamus reiciendis maiores. Qui iure deserunt, dignissimos distinctio aut, at nobis in laudantium natus voluptatibus magni id, mollitia neque! Eos, magni.",
    category: "4",
    active: "Yes",
  },
  {
    _id: "12",
    cover: "../img/food/s2.jpg",
    name: "Sandwich",
    price: "50",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum ipsa voluptates, iste quisquam, explicabo quos illum dicta iure libero fugit distinctio! Voluptate voluptas illum esse? Placeat accusantium impedit recusandae ratione. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates accusamus reiciendis maiores. Qui iure deserunt, dignissimos distinctio aut, at nobis in laudantium natus voluptatibus magni id, mollitia neque! Eos, magni.",
    category: "1",
    active: "Yes",
  },
  {
    _id: "13",
    cover: "../img/food/b1.jpg",
    name: "Burger",
    price: "60",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum ipsa voluptates, iste quisquam, explicabo quos illum dicta iure libero fugit distinctio! Voluptate voluptas illum esse? Placeat accusantium impedit recusandae ratione. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates accusamus reiciendis maiores. Qui iure deserunt, dignissimos distinctio aut, at nobis in laudantium natus voluptatibus magni id, mollitia neque! Eos, magni.",
    category: "4",
    active: "Yes",
  },
  {
    _id: "14",
    cover: "../img/food/p1.jpg",
    name: "Pizza",
    price: "200",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum ipsa voluptates, iste quisquam, explicabo quos illum dicta iure libero fugit distinctio! Voluptate voluptas illum esse? Placeat accusantium impedit recusandae ratione. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates accusamus reiciendis maiores. Qui iure deserunt, dignissimos distinctio aut, at nobis in laudantium natus voluptatibus magni id, mollitia neque! Eos, magni.",
    category: "1",
    active: "Yes",
  },
  {
    _id: "15",
    cover: "../img/food/s1.jpg",
    name: "Sandwich",
    price: "50",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum ipsa voluptates, iste quisquam, explicabo quos illum dicta iure libero fugit distinctio! Voluptate voluptas illum esse? Placeat accusantium impedit recusandae ratione. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates accusamus reiciendis maiores. Qui iure deserunt, dignissimos distinctio aut, at nobis in laudantium natus voluptatibus magni id, mollitia neque! Eos, magni.",
    category: "3",
    active: "Yes",
  },
  {
    _id: "16",
    cover: "../img/food/b2.jpg",
    name: "Burger",
    price: "60",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum ipsa voluptates, iste quisquam, explicabo quos illum dicta iure libero fugit distinctio! Voluptate voluptas illum esse? Placeat accusantium impedit recusandae ratione. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates accusamus reiciendis maiores. Qui iure deserunt, dignissimos distinctio aut, at nobis in laudantium natus voluptatibus magni id, mollitia neque! Eos, magni.",
    category: "2",
    active: "Yes",
  },
  {
    _id: "17",
    cover: "../img/food/p2.jpg",
    name: "Pizza",
    price: "200",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum ipsa voluptates, iste quisquam, explicabo quos illum dicta iure libero fugit distinctio! Voluptate voluptas illum esse? Placeat accusantium impedit recusandae ratione. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates accusamus reiciendis maiores. Qui iure deserunt, dignissimos distinctio aut, at nobis in laudantium natus voluptatibus magni id, mollitia neque! Eos, magni.",
    category: "1",
    active: "Yes",
  },
  {
    _id: "18",
    cover: "../img/food/s2.jpg",
    name: "Sandwich",
    price: "50",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum ipsa voluptates, iste quisquam, explicabo quos illum dicta iure libero fugit distinctio! Voluptate voluptas illum esse? Placeat accusantium impedit recusandae ratione. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates accusamus reiciendis maiores. Qui iure deserunt, dignissimos distinctio aut, at nobis in laudantium natus voluptatibus magni id, mollitia neque! Eos, magni.",
    category: "4",
    active: "Yes",
  },
];

export const blog = [
  {
    _id: "1",
    type: "admin",
    date: "JAN. 18, 2021",
    title: "Build your Dream Software and Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus.",
    cover: "../img/blog/b1.jpg",
  },
  {
    _id: "2",
    type: "admin",
    date: "API. 25, 2022",
    title: "Build your Dream Software and Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus.",
    cover: "../img/blog/b2.jpg",
  },
  {
    _id: "3",
    type: "user",
    date: "MAY. 15, 2022",
    title: "Build your Dream Software and Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus.",
    cover: "../img/blog/b3.jpg",
  },
  {
    _id: "4",
    type: "admin",
    date: "JAN. 02, 2022",
    title: "Build your Dream Software and Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus.",
    cover: "../img/blog/b4.jpg",
  },
  {
    _id: "5",
    type: "admin",
    date: "DEC. 14, 2022",
    title: "Build your Dream Software and Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus.",
    cover: "../img/blog/b5.jpg",
  },
  {
    _id: "6",
    type: "user",
    date: "JAN. 18, 2021",
    title: "Build your Dream Software and Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium nam, quibusdam ipsam, eum maiores temporibus delectus atque labore accusamus ipsa, fugiat dolor molestiae? Reiciendis expedita maxime quibusdam ullam cum natus.",
    cover: "../img/blog/b6.jpg",
  },
];
export const order = [
  {
    cover: "./img/shopping-cart.jpg",
    name: "Pizza",
    price: 200,
    qty: 1,
    total: 200,
    date: "(8pm) 25/10/2022",
    deliverd: "2hr",
    status: "Ordered",
  },
  {
    cover: "./img/shopping-cart.jpg",
    name: "Pizza",
    price: 200,
    qty: 1,
    total: 200,
    date: "(8pm) 25/10/2022",
    deliverd: "2hr",
    status: "Ordered",
  },
  {
    cover: "./img/shopping-cart.jpg",
    name: "Pizza",
    price: 200,
    qty: 1,
    total: 200,
    date: "(8pm) 25/10/2022",
    deliverd: "2hr",
    status: "Ordered",
  },
  {
    cover: "./img/shopping-cart.jpg",
    name: "Pizza",
    price: 200,
    qty: 1,
    total: 200,
    date: "(8pm) 25/10/2022",
    deliverd: "2hr",
    status: "Ordered",
  },
];
